#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "@daypaw/* 首次发布（ADR 0011 客户自跑交付）"

# ── Stage 1: npm 账号与 @daypaw scope ─────────────────────────────────────
stage "npm：账号与 @daypaw scope"
say "包的 scope 是 @daypaw，它在 npm 上要么是你的用户名 scope，要么归你名下的组织。"
say "用户名是 0xnicholas，所以 @daypaw 必须是一个名为 daypaw 的组织（org）。"
open_url "https://www.npmjs.com/org/daypaw"
step "如果这个页面显示的组织归你 → 直接回车继续。"
step "如果显示 404 / 不存在 → 创建它：头像 → Add an Organization → Name 填 daypaw"
note "  → 计划选 Unlimited public packages（免费）→ Create。"
step "如果这个名字已被别人占用 → 现在 Ctrl-C 停下。那是项目级决策：所有包名都要改，不是这一步能解决的。"
pause "确认 @daypaw 归你之后，按回车继续。"

# ── Stage 2: 生成 granular access token ───────────────────────────────────
stage "npm：生成发布用 token"
say "CI 里的 npm publish 需要一个能直接发布的 granular access token。"
open_url "https://www.npmjs.com/settings/0xnicholas/tokens"
step "点 Generate New Token；Token name 填 daypaw-release。"
step "勾选 Bypass two-factor authentication —— 这是 CI 直接发布的硬要求（没有它，npm 会要求交互式 2FA）。"
step "Packages and scopes → Permissions 选 Read and write (publish and stage)。"
step "Select Packages 选 Only select packages and scopes，然后在选择器里选 @daypaw。"
step "Expiration 选一个期限（到期后重跑本向导）。"
step "点 Generate Token，然后立刻复制 —— 完整 token 只显示这一次。"
ask_secret NPM_TOKEN "粘贴 token："
note "本向导故意不把 token 写进 .env：它是 CI 凭据，本地开发流程不读它，写进去只会让它出现在每个本地进程里。"

# ── Stage 3: 写进 GitHub secret ───────────────────────────────────────────
stage "GitHub：写 NPM_TOKEN secret"
say "release-daypaw.yml 的 publish job 只读一个 secret，就是它。"
set_secret NPM_TOKEN "$NPM_TOKEN"
step "确认已写入：gh secret list --repo 0xnicholas/daypaw-pro"

# ── Stage 4: 触发发布 ─────────────────────────────────────────────────────
stage "触发发布工作流"
say "pack job 不需要凭据，会先构建两个包、装进临时 prefix、真起一次壳、再跑一次 SDK 消费方。"
say "只有 publish job 用 NPM_TOKEN，并且仅在手动触发的 publish=true 时运行。"
note "本次发布的是两个 0.1.0。之后每次发布前要先抬 packages/daypaw/{cli,sdk}/package.json 的 version。"
if confirm "现在触发发布（会真的发到 npm，不可撤回）？"; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh workflow run release-daypaw.yml -f publish=true \
      && say "已触发。看进度：gh run watch \$(gh run list --workflow release-daypaw.yml --limit 1 --json databaseId --jq '.[0].databaseId')"
  else
    warn "gh 不可用，手动触发：gh workflow run release-daypaw.yml -f publish=true"
  fi
else
  note "跳过。稍后手动触发：gh workflow run release-daypaw.yml -f publish=true"
fi

# ── Stage 5: 发布后验证 ───────────────────────────────────────────────────
stage "验证：registry 上真的有这两个包"
say "等工作流两个 job 都绿之后再做这一步。"
pause "工作流跑完了就按回车，向导会去 registry 查版本。"
if command -v npm >/dev/null 2>&1; then
  for pkg in @daypaw/cli @daypaw/sdk; do
    v=$(npm view "$pkg" version --fetch-timeout=8000 --fetch-retries=0 2>/dev/null || true)
    if [[ -n "$v" ]]; then say "$pkg → $v"; else warn "$pkg 还查不到；先看 gh run list --workflow release-daypaw.yml"; fi
  done
fi
say "最后一步的真检验：在一台没有本仓库的机器上 npm i -g @daypaw/cli && daypaw。"

finish
